import './globals.css';

export const metadata = {
	title: 'Curology',
	description: 'Generated by create next app',
	creator: 'Klevert Opee',
};
export const viewport = {
	themeColor: 'rgb(252,211,77)',
};

export default function RootLayout({children}) {
	return (
		<html lang="en">
		<body>{children}</body>
		</html>
	);
}

