import '@/src/app/globals.css';
import ScrollThumb from '@/src/components/Ui/ScrollThumb';
import localFont from 'next/font/local';

export const metadata = {
  title: 'Curology',
  description: 'Generated by create next app',
  creator: 'Klevert Opee'
};
export const viewport = {
  themeColor: 'rgb(252,211,77)'
};

const Expose = localFont (
  {
    src: 'assets/font/Expose-Variable.woff2',
    style: 'normal',
    display: 'swap'
  }
);

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
    <body className={Expose.className}>
    <div id='smooth-wrapper'>
      <div id='smooth-content'
           className='relative'>
        {children}
      </div>
    </div>
    <ScrollThumb />
    </body>
    </html>
  );
}
