import localFont from "next/font/local";
import "@/src/app/globals.css";
import React from "react";

const metadata = {
	title: 'Curology',
	description: 'Generated by create next app',
	creator: 'Klevert Opee'
};

const viewport = {
	themeColor: 'rgb(240,240,240)'
};

const Expose = localFont({
	src: 'assets/font/Expose-Variable.woff2',
	style: 'normal',
	display: 'swap'
});

interface RootLayoutProps {
	children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang='en'>
		<body className={Expose.className}>
		{children}
		</body>
		</html>
	);
};

export { metadata, viewport };
export default RootLayout;
